USE library_db;

LOAD DATA INFILE '/var/lib/mysql-files/USER.csv' INTO TABLE USER
FIELDS TERMINATED BY ',' 
ENCLOSED BY '"' 
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(EMAIL, FIRST_NAME, LAST_NAME, ADDRESS, PHONE_NUMBER, HASH, ADMIN);

LOAD DATA INFILE '/var/lib/mysql-files/CATALOG_ITEM.csv' INTO TABLE CATALOG_ITEM
FIELDS TERMINATED BY ',' 
ENCLOSED BY '"' 
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(ID, TITLE, DATE);

LOAD DATA INFILE '/var/lib/mysql-files/MOVIE.csv' INTO TABLE MOVIE
FIELDS TERMINATED BY ',' 
ENCLOSED BY '"' 
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(CATALOG_ITEM_ID, DIRECTOR, PRODUCERS, ACTORS, LANGUAGE, SUBTITLES, DUBBED, RUNTIME);