USE library_db;

LOAD DATA INFILE '/var/lib/mysql-files/ACCOUNTS.csv' INTO TABLE ACCOUNT
FIELDS TERMINATED BY ',' 
ENCLOSED BY '"' 
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(EMAIL, FIRST_NAME, LAST_NAME, ADDRESS, PHONE_NUMBER, HASH, ADMIN);