USE library_db;

LOAD DATA INFILE '/var/lib/mysql-files/USER.csv' INTO TABLE USER
FIELDS TERMINATED BY ',' 
ENCLOSED BY '"' 
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(EMAIL, FIRST_NAME, LAST_NAME, ADDRESS, PHONE_NUMBER, HASH, ADMIN);

LOAD DATA INFILE '/var/lib/mysql-files/CATALOG_ITEM.csv' INTO TABLE CATALOG_ITEM
FIELDS TERMINATED BY ',' 
ENCLOSED BY '"' 
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(ID, TITLE, DATE);

LOAD DATA INFILE '/var/lib/mysql-files/MOVIE.csv' INTO TABLE MOVIE
FIELDS TERMINATED BY ',' 
ENCLOSED BY '"' 
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(CATALOG_ITEM_ID, DIRECTOR, PRODUCERS, ACTORS, LANGUAGE, SUBTITLES, DUBBED, RUNTIME);

LOAD DATA INFILE '/var/lib/mysql-files/MUSIC.csv' INTO TABLE MUSIC
FIELDS TERMINATED BY ',' 
ENCLOSED BY '"' 
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(CATALOG_ITEM_ID, TYPE, ARTIST, LABEL, ASIN);

LOAD DATA INFILE '/var/lib/mysql-files/BOOK.csv' INTO TABLE BOOK
FIELDS TERMINATED BY ',' 
ENCLOSED BY '"' 
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(CATALOG_ITEM_ID, ISBN_10, ISBN_13, AUTHOR, PUBLISHER, FORMAT, PAGES);

LOAD DATA INFILE '/var/lib/mysql-files/MAGAZINE.csv' INTO TABLE MAGAZINE
FIELDS TERMINATED BY ',' 
ENCLOSED BY '"' 
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(CATALOG_ITEM_ID, ISBN_10, ISBN_13, PUBLISHER, LANGUAGE);