-- MySQL Script generated by MySQL Workbench
-- Fri 23 Nov 2018 12:13:40 AM EST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema library_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema library_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `library_db` DEFAULT CHARACTER SET utf8 ;
USE `library_db` ;

-- -----------------------------------------------------
-- Table `library_db`.`USER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library_db`.`USER` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `EMAIL` VARCHAR(45) NOT NULL,
  `FIRST_NAME` VARCHAR(45) NOT NULL,
  `LAST_NAME` VARCHAR(100) NOT NULL,
  `ADDRESS` VARCHAR(45) NOT NULL,
  `PHONE_NUMBER` CHAR(10) NOT NULL,
  `HASH` CHAR(160) NOT NULL,
  `ADMIN` TINYINT NOT NULL DEFAULT 0,
  `SESSION_ID` CHAR(36) NULL,
  `LAST_LOGIN` TIMESTAMP NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `library_db`.`CATALOG_ITEM`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library_db`.`CATALOG_ITEM` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `TITLE` VARCHAR(45) NOT NULL,
  `DATE` TIMESTAMP NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `library_db`.`BOOK`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library_db`.`BOOK` (
  `ISBN_10` CHAR(10) NOT NULL,
  `ISBN_13` CHAR(13) NOT NULL,
  `AUTHOR` VARCHAR(45) NOT NULL,
  `PUBLISHER` VARCHAR(45) NOT NULL,
  `FORMAT` VARCHAR(45) NOT NULL,
  `PAGES` INT NOT NULL,
  `CATALOG_ITEM_ID` INT NOT NULL,
  PRIMARY KEY (`CATALOG_ITEM_ID`),
  CONSTRAINT `fk_BOOK_CATALOG_ITEM1`
    FOREIGN KEY (`CATALOG_ITEM_ID`)
    REFERENCES `library_db`.`CATALOG_ITEM` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `library_db`.`MAGAZINE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library_db`.`MAGAZINE` (
  `ISBN_10` CHAR(10) NOT NULL,
  `ISBN_13` CHAR(13) NOT NULL,
  `PUBLISHER` VARCHAR(45) NOT NULL,
  `LANGUAGE` VARCHAR(45) NOT NULL,
  `CATALOG_ITEM_ID` INT NOT NULL,
  PRIMARY KEY (`CATALOG_ITEM_ID`),
  CONSTRAINT `fk_MAGAZINE_CATALOG_ITEM1`
    FOREIGN KEY (`CATALOG_ITEM_ID`)
    REFERENCES `library_db`.`CATALOG_ITEM` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `library_db`.`MUSIC`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library_db`.`MUSIC` (
  `TYPE` VARCHAR(45) NOT NULL,
  `ARTIST` VARCHAR(45) NOT NULL,
  `LABEL` VARCHAR(45) NOT NULL,
  `ASIN` VARCHAR(45) NOT NULL,
  `CATALOG_ITEM_ID` INT NOT NULL,
  PRIMARY KEY (`CATALOG_ITEM_ID`),
  CONSTRAINT `fk_MUSIC_CATALOG_ITEM1`
    FOREIGN KEY (`CATALOG_ITEM_ID`)
    REFERENCES `library_db`.`CATALOG_ITEM` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `library_db`.`MOVIE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library_db`.`MOVIE` (
  `DIRECTOR` VARCHAR(45) NOT NULL,
  `PRODUCERS` VARCHAR(256) NOT NULL,
  `ACTORS` VARCHAR(256) NOT NULL,
  `LANGUAGE` VARCHAR(45) NOT NULL,
  `SUBTITLES` VARCHAR(45) NOT NULL,
  `DUBBED` VARCHAR(45) NOT NULL,
  `RUNTIME` INT NOT NULL,
  `CATALOG_ITEM_ID` INT NOT NULL,
  PRIMARY KEY (`CATALOG_ITEM_ID`),
  INDEX `fk_MOVIE_CATALOG_ITEM_idx` (`CATALOG_ITEM_ID` ASC),
  CONSTRAINT `fk_MOVIE_CATALOG_ITEM`
    FOREIGN KEY (`CATALOG_ITEM_ID`)
    REFERENCES `library_db`.`CATALOG_ITEM` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `library_db`.`INVENTORY_ITEM`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library_db`.`INVENTORY_ITEM` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `CATALOG_ITEM_ID` INT NOT NULL,
  `LOANED_TO` INT NULL,
  `DUE_DATE` TIMESTAMP NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_INVENTORY_CATALOG_ITEM1_idx` (`CATALOG_ITEM_ID` ASC),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC),
  INDEX `fk_INVENTORY_ITEM_USER1_idx` (`LOANED_TO` ASC),
  CONSTRAINT `fk_INVENTORY_CATALOG_ITEM1`
    FOREIGN KEY (`CATALOG_ITEM_ID`)
    REFERENCES `library_db`.`CATALOG_ITEM` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_INVENTORY_ITEM_USER1`
    FOREIGN KEY (`LOANED_TO`)
    REFERENCES `library_db`.`USER` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `library_db`.`TRANSACTION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library_db`.`TRANSACTION` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `TIMESTAMP` TIMESTAMP NOT NULL,
  `OPERATION` VARCHAR(45) NOT NULL,
  `INVENTORY_ITEM_ID` INT NOT NULL,
  `USER_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_TRANSACTION_USER1_idx` (`USER_ID` ASC),
  CONSTRAINT `fk_TRANSACTION_USER1`
    FOREIGN KEY (`USER_ID`)
    REFERENCES `library_db`.`USER` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
